include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_final_locals: true
    always_use_package_imports: true
    avoid_print: true
    cancel_subscriptions: true
    sized_box_for_whitespace: true
    unnecessary_lambdas: true